### ISSUE TITLE
Error during mark price subscription event: -> SQLState: null

### ISSUE THREAD

**Issue by danielvm-git** [ebaloaloa/lick-hunter-server#103]
**Describe the bug**
In recent weeks, once a day the LHS stopped working and threw the error below. Since yesterday it has entered the error right after the bot starts, throws the exception, and in the sequence, it enters in an infinite loop repeating the last 2 lines of the stack trace below:

anyone else getting the same error?

```bash
2021-10-02 00:38:43,688 INFO  [main] com.lickhunter.web.services.impl.MarketServiceImpl: Retrieving Exchange Information
2021-10-02 00:38:44,102 INFO  [main] com.lickhunter.web.services.impl.MarketServiceImpl: Retrieving 24h Ticker Price Change
2021-10-02 00:38:44,386 INFO  [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][0] Connected to server
2021-10-02 00:38:44,914 INFO  [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][1] Connected to server
2021-10-02 00:38:45,092 INFO  [main] com.lickhunter.web.services.impl.MarketServiceImpl: Retrieving liquidation data.
2021-10-02 00:39:17,187 WARN  [main] org.springframework.context.support.AbstractApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webApplication': Invocation of init method failed; nested exception is org.springframework.web.client.UnknownHttpStatusCodeException: 522 : [no body]
2021-10-02 00:39:17,188 INFO  [main] org.springframework.scheduling.concurrent.ExecutorConfigurationSupport: Shutting down ExecutorService 'applicationTaskExecutor'
2021-10-02 00:39:17,188 INFO  [main] org.springframework.orm.jpa.AbstractEntityManagerFactoryBean: Closing JPA EntityManagerFactory for persistence unit 'default'
2021-10-02 00:39:17,191 INFO  [main] com.zaxxer.hikari.HikariDataSource: springHikariCP - Shutdown initiated...
2021-10-02 00:39:17,192 INFO  [task-1] com.binance.client.impl.WebSocketConnection: [Sub] Connection [id: 2] created for ***Candlestick for [btcusdt, ethusdt, bchusdt, xrpusdt, eosusdt, ltcusdt, trxusdt, etcusdt, linkusdt, xlmusdt, adausdt, xmrusdt, dashusdt, zecusdt, xtzusdt, bnbusdt, atomusdt, ontusdt, iotausdt, batusdt, vetusdt, neousdt, qtumusdt, iostusdt, thetausdt, algousdt, zilusdt, kncusdt, zrxusdt, compusdt, omgusdt, dogeusdt, sxpusdt, kavausdt, bandusdt, rlcusdt, wavesusdt, mkrusdt, snxusdt, dotusdt, defiusdt, yfiusdt, balusdt, crvusdt, trbusdt, yfiiusdt, runeusdt, sushiusdt, srmusdt, bzrxusdt, egldusdt, solusdt, icxusdt, storjusdt, blzusdt, uniusdt, avaxusdt, ftmusdt, hntusdt, enjusdt, flmusdt, tomousdt, renusdt, ksmusdt, nearusdt, aaveusdt, filusdt, rsrusdt, lrcusdt, maticusdt, oceanusdt, cvcusdt, belusdt, ctkusdt, axsusdt, alphausdt, zenusdt, sklusdt, grtusdt, 1inchusdt, akrousdt, chzusdt, sandusdt, ankrusdt, lunausdt, btsusdt, litusdt, unfiusdt, dodousdt, reefusdt, rvnusdt, sfpusdt, xemusdt, btcstusdt, cotiusdt, chrusdt, manausdt, aliceusdt, hbarusdt, oneusdt, linausdt, stmxusdt, dentusdt, celrusdt, hotusdt, mtlusdt, ognusdt, bttusdt, nknusdt, scusdt, dgbusdt, 1000shibusdt, icpusdt, bakeusdt, gtcusdt, btcdomusdt, keepusdt, tlmusdt, iotxusdt, audiousdt, rayusdt, c98usdt, maskusdt, atausdt, dydxusdt, 1000xecusdt, galausdt, celousdt, arusdt]***
2021-10-02 00:39:17,193 INFO  [task-1] com.binance.client.impl.WebSocketConnection: [Sub][2] Connecting...
2021-10-02 00:39:17,193 INFO  [main] com.zaxxer.hikari.HikariDataSource: springHikariCP - Shutdown completed.
2021-10-02 00:39:17,193 INFO  [task-1] com.binance.client.impl.WebSocketConnection: [Sub] Connection [id: 3] created for ***Candlestick for [btcusdt, ethusdt, bchusdt, xrpusdt, eosusdt, ltcusdt, trxusdt, etcusdt, linkusdt, xlmusdt, adausdt, xmrusdt, dashusdt, zecusdt, xtzusdt, bnbusdt, atomusdt, ontusdt, iotausdt, batusdt, vetusdt, neousdt, qtumusdt, iostusdt, thetausdt, algousdt, zilusdt, kncusdt, zrxusdt, compusdt, omgusdt, dogeusdt, sxpusdt, kavausdt, bandusdt, rlcusdt, wavesusdt, mkrusdt, snxusdt, dotusdt, defiusdt, yfiusdt, balusdt, crvusdt, trbusdt, yfiiusdt, runeusdt, sushiusdt, srmusdt, bzrxusdt, egldusdt, solusdt, icxusdt, storjusdt, blzusdt, uniusdt, avaxusdt, ftmusdt, hntusdt, enjusdt, flmusdt, tomousdt, renusdt, ksmusdt, nearusdt, aaveusdt, filusdt, rsrusdt, lrcusdt, maticusdt, oceanusdt, cvcusdt, belusdt, ctkusdt, axsusdt, alphausdt, zenusdt, sklusdt, grtusdt, 1inchusdt, akrousdt, chzusdt, sandusdt, ankrusdt, lunausdt, btsusdt, litusdt, unfiusdt, dodousdt, reefusdt, rvnusdt, sfpusdt, xemusdt, btcstusdt, cotiusdt, chrusdt, manausdt, aliceusdt, hbarusdt, oneusdt, linausdt, stmxusdt, dentusdt, celrusdt, hotusdt, mtlusdt, ognusdt, bttusdt, nknusdt, scusdt, dgbusdt, 1000shibusdt, icpusdt, bakeusdt, gtcusdt, btcdomusdt, keepusdt, tlmusdt, iotxusdt, audiousdt, rayusdt, c98usdt, maskusdt, atausdt, dydxusdt, 1000xecusdt, galausdt, celousdt, arusdt]***
2021-10-02 00:39:17,193 INFO  [task-1] com.binance.client.impl.WebSocketConnection: [Sub][3] Connecting...
2021-10-02 00:39:17,193 INFO  [task-1] com.lickhunter.web.websockets.BinanceSubscription: Subscribed to Binance Candlestick data
2021-10-02 00:39:17,194 INFO  [main] org.apache.juli.logging.DirectJDKLog: Stopping service [Tomcat]
2021-10-02 00:39:17,203 INFO  [main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-02 00:39:17,223 ERROR [main] org.springframework.boot.SpringApplication: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webApplication': Invocation of init method failed; nested exception is org.springframework.web.client.UnknownHttpStatusCodeException: 522 : [no body]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.lickhunter.web.WebApplication.main(WebApplication.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.web.client.UnknownHttpStatusCodeException: 522 : [no body]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:123)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
	at com.lickhunter.web.services.impl.MarketServiceImpl.getLiquidations(MarketServiceImpl.java:201)
	at com.lickhunter.web.WebApplication.initProcess(WebApplication.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 27 common frames omitted
2021-10-02 00:39:17,268 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during mark price subscription event: %s
2021-10-02 00:39:17,269 ERROR [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][0] Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:18,245 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during mark price subscription event: %s
2021-10-02 00:39:18,246 ERROR [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][0] Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,149 INFO  [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][3] Connected to server
2021-10-02 00:39:19,259 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during mark price subscription event: %s
2021-10-02 00:39:19,260 ERROR [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][0] Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,492 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during candlestick subscription event: Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,493 ERROR [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][3] Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,498 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during candlestick subscription event: Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,498 ERROR [OkHttp https://fstream.binance.com/...] com.binance.client.impl.WebSocketConnection: [Sub][3] Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler
2021-10-02 00:39:19,507 ERROR [OkHttp https://fstream.binance.com/...] com.lickhunter.web.websockets.BinanceSubscription: Error during candlestick subscription event: Process error: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed You should capture the exception in your error handler

````

**To Reproduce**
1. On the last 3 days it's just about starting the bot and the system throws the error 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Latest Release

**Additional context**
Using this settings.json:

```bash
{
  "exchange": "binance",
  "key": "mykey",
  "secret": "mysecret",
  "auto_qty": "True",
  "longQty": "0.1",
  "shortQty": "0.1",
  "percentBal": "0.1",
  "maxPosition": "50",
  "dcaOne": "3",
  "factorOne": "2",
  "dcaTwo": "6",
  "factorTwo": "4",
  "leverage": "5",
  "takeprofit": "0.5",
  "stoploss": "1",
  "auth": "ALPHA",
  "delay": "0.5",
  "discordwebhook": "webhookhere",
  "sleeponstop": "1"
}
````

**Comment by raulnavarro82** [comment]
I'm getting the same error using windows server, and everyone I know using LHS is having the same error.

**Comment by ebaloaloa** [comment]
What version are you using?  Try updating to latest version.

**Comment by raulnavarro82** [comment]
Using 0.12.5 and updated to 0.12.5, i have to replace jar and db or everything?

The error that shows is:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-01 20:10:13,062 ERROR org.springframework.boot.SpringApplication [main] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webApplication': Invocation of init method failed; nested exception is org.springframework.web.client.UnknownHttpStatusCodeException: 522 : [no body]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.lickhunter.web.WebApplication.main(WebApplication.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.web.client.UnknownHttpStatusCodeException: 522 : [no body]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:123)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
	at com.lickhunter.web.services.impl.MarketServiceImpl.getLiquidations(MarketServiceImpl.java:201)
	at com.lickhunter.web.WebApplication.initProcess(WebApplication.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 27 common frames omitted

**Comment by raulnavarro82** [comment]
Now it works!
